Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
choco install 7zip.install curl -y; RefreshEnv;
mkdir $env:tmp/jdk;
cd $env:tmp/jdk;
$version = curl -s https://api.adoptium.net/v3/info/available_releases | findstr.exe "most_recent_feature_release" | cut -c 36-37;
$first = "https://api.adoptium.net/v3/binary/latest/";
$second = "/ga/windows/x64/jdk/hotspot/normal/eclipse?project=jdk";
curl -L -0 $first$version$second -o "jdk.zip";
set-alias sz "$env:ProgramFiles\7-Zip\7z.exe";
sz x "jdk.zip" -r;
rm "jdk.zip";
$name = Get-ChildItem . | Select-Object -ExpandProperty Name;
mv $name "C:\jdk\";
rmdir $env:tmp/jdk;
setx -m JAVA_HOME "C:\jdk"; RefreshEnv;
$env:Path += ";%PATH%;%JAVA_HOME%\bin"; RefreshEnv;
java --version;
pause;
exit;